---

is_debug: true

listen:
  type: port
  bind_ip: 0.0.0.0
  port: :8080

storage:
  host: localhost
  port: 5432
  database: postgres
  username: postgres

alchemy:
  mode: history
  start: 22488000
  end: 22489220
  network_name: ethereum
  name_api_key: ALCHEMY_API_KEY
  limiter: 25
  max_retries: 5
  batch_size: 500
  workers: 8